name: Publish Changes

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/configure-pages@v5
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        # TODO: Disabling 'with' section to see if
        # (a) this works
        # and
        # (b) we can use the dot prefix when linking files
        #with:
        #  path: "."
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4